### ISSUE TITLE
Usage for apps not using Brotli compression

### ISSUE THREAD

**Issue by jbailey4** [kaliber5/ember-cli-bundlesize#8]
Thanks for the great addon!

Could there be a way to make `brotli-size` an optional dependency for those that only use `gzip` exclusively in their projects? This dep pulls in `iltorb` which requires native OS bindings, and while this is possible to set up, it requires extra effort to configure for CI for something that isn't relevant for the consuming app.

Similar issues: https://github.com/siddharthkp/bundlesize/issues/202

**Comment by simonihmig** [comment]
Thanks @jbailey4 for this suggestion, I agree it makes sense!

The approach could be similar to https://github.com/siddharthkp/bundlesize/pull/220, i.e. remove the package from `dependencies`, check when running the test command that brotli is not used in the configuration, or if it is that `brotli-size` is available, otherwise fail with an error message like `Please install brotli-size if you want to use ember-cli-bundlesize with Brotli`.
 
Would you eventually be interested in contributing this PR?

**Comment by jbailey4** [comment]
@simonihmig Sure! Thanks for the suggestions. I'll try to find some time this weekend.
